version: "3.8"
services:
  mongodb:
    image: "mongo"
    ports:
    - "27017:27017"
    # volumes:
    #   - data:/data/db
    networks:
      - mern-network
    container_name: mongo-db

  backend:
    build: ./backend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - mongodb
    networks:
      - mern-network
    container_name: node-api
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network
    container_name: react-ui

networks:
  mern-network:
   driver: bridge
